### ISSUE TITLE
Add the word "ngoạ"

### ISSUE THREAD

**Issue by ngoclong19** [1ec5/hunspell-vi#10]
Currently there isn't the word "ngoạ" (as in "ngoạ hổ tàng long") in the dictionary (old and new ways). I think it should be added.

**Comment by 1ec5** [comment]
Is “ngọa hổ tàng long” used as an idiom in Vietnamese (besides the film title)? Is “ngọa” used in any other contexts? The wordlist currently omits many words that only appear in Hán-Việt compounds, because unfortunately checking compound words isn’t feasible with the current setup. (It’s a trade-off between accepting Hán-Việt words and failing to flag misspelled thuần Việt words.)
