### ISSUE TITLE
Add the word "huế"

### ISSUE THREAD

**Issue by ngoclong19** [1ec5/hunspell-vi#16]
Currently there isn't the word "huế" (as in "thành phố huế") in the dictionary (old and new ways). I think it should be added.

**Comment by 1ec5** [comment]
Hi, you’re right, it would be great if the dictionary would include Huế (capitalized). #3 tracks adding major place names, but Huế is somewhat more straightforward because it’s only a single syllable.

“Huế” would be added right about here (sorted according to Unicode codepoint rather than alphabetized):

https://github.com/1ec5/hunspell-vi/blob/1823f4e6ab92d45739bf2223d8f30ca1c3e5519a/dictionaries/vi-DauCu.dic#L7-L8 https://github.com/1ec5/hunspell-vi/blob/1823f4e6ab92d45739bf2223d8f30ca1c3e5519a/dictionaries/vi-DauMoi.dic#L7-L8
